### ISSUE TITLE
Home Assistant 109.0 possibly breaks plugin?

### ISSUE THREAD

**Issue by whitwhittle** [briis/smartweather#31]
Having issues with Plugin following 109.0 upgrade.  Worked fine with 108.9

When I run Configuration Validation, get the following message:

Platform error sensor.smartweather - cannot import name 'UNIT_UV_INDEX' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

If I comment out the sensor: smartweather line in configuration.yaml, I don't get any errors (but of course, I dont have access to sensors).

**Comment by briis** [comment]
UNIT_UV_INDEX has been replaced by UV_INDEX in HA Constants with 109. Easy to fix. I will release an update tomorrow.

**Comment by lubbertkramer** [comment]
> UNIT_UV_INDEX has been replaced by UV_INDEX in HA Constants with 109. Easy to fix. I will release an update tomorrow.

Great to see you still maintain this component! How are you going to support this in the future, will you accept fixed made by the community to keep this addon active (here a weatherflow user)

**Comment by briis** [comment]
The breaking change has now been fixed, and there will be a release 1.0.4 available in HACS soon.

@lubbertkramer: I can still support this component, even without the station running locally, as this uses the REST API, and I can just pick another public weather staton to test on. I made a UDP version also, and that one I cannot support anymore, as this requires local HW.
Eventually, this component might require major rework, if HA implements new requirements, and by then I am not sure I will do all the work.

**Comment by briis** [comment]
Closing this .

**Comment by briis** [comment]
@lubbertkramer: Sorry I did not really answer your question. YES I would love for other people to step in. No doubt this would benefit from some rewrites, and constant maintenance, so all help is appreciated. 

Remember, that the communication with the API comes from *pysmartweather'* so that also needs some *love* - this was the first thing I ever did in Python, so I know that would benefit from a lot of refactoring

Ideally, converting both modules to using *async* would be the right thing to do.

**Comment by lubbertkramer** [comment]
@briis Great to hear, i will keep that in mind and take a look at your code (not the best expert though :) ). I will keep in mind when there will be changes

**Comment by briis** [comment]
My plan now, is to rewrite both the API module (pysmartweatherio) and this component, so that it runs completely Async, and better conforms to HA standards. During that process my plan is to remove the *weather* part of this component, as DarkSky will not be available in the future, leaving Binary Sensors and Sensors. I will also move to a real Integration, so that configuration will be done from the GUI.

Any thoughts on that?

**Comment by briis** [comment]
I am now almost done with rewriting the whole Integration. While waiting another user actually found out that WeatherFlow also has a Rest API for their new Forecast Data, so besides new Config Flow setup and Async Support, I have now also replaced DarkSky, with WeatherFlows own Forecast data. 
HACS will be updated when I have re-written the documentation, but feel free to test by downloading the files in the master branch - **remember** to remove all `yaml` references for `smartweather` before you try this out.
